// Generated by dts-bundle-generator v9.5.1

import { Elysia } from 'elysia';
import { ColumnType, Selectable } from 'kysely';
import z$1 from 'zod';
import { z } from 'zod';

declare const auth: import("better-auth").Auth<{
	database: import("pg").Pool;
	baseURL: {
		allowedHosts: string[];
		fallback: string;
	};
	basePath: string;
	secret: string;
	trustedOrigins: string[];
	onAPIError: {
		errorURL: string;
	};
	advanced: {
		useSecureCookies: boolean;
		ipAddress: {
			ipAddressHeaders: string[];
			trustedProxies: string[];
		};
	};
	disabledPaths: string[];
	account: {
		encryptOAuthTokens: true;
	};
	user: {
		validateUserInfo: ({ user, source }: {
			user: Partial<import("better-auth").User> & Record<string, unknown>;
			source: import("better-auth").ValidateUserInfoSource;
		}) => {
			error: string;
			errorDescription: string;
		} | undefined;
		additionalFields: {
			gitlabUsername: {
				type: "string";
				required: false;
			};
		};
	};
	databaseHooks: {
		user: {
			create: {
				before: (user: {
					id: string;
					createdAt: Date;
					updatedAt: Date;
					email: string;
					emailVerified: boolean;
					name: string;
					image?: string | null | undefined;
				} & Record<string, unknown>, context: import("better-auth").GenericEndpointContext | null) => Promise<{
					data: {
						[x: string]: unknown;
					};
				} | undefined>;
			};
			update: {
				before: (user: Partial<{
					id: string;
					createdAt: Date;
					updatedAt: Date;
					email: string;
					emailVerified: boolean;
					name: string;
					image?: string | null | undefined;
				}> & Record<string, unknown>, context: import("better-auth").GenericEndpointContext | null) => Promise<{
					data: {
						[x: string]: unknown;
					};
				} | undefined>;
			};
		};
	};
	plugins: [
		{
			id: "custom-session";
			version: string;
			hooks: {
				after: {
					matcher: (ctx: import("better-auth").HookEndpointContext) => boolean;
					handler: import("better-auth").Middleware<import("better-auth").MiddlewareOptions, (inputContext: import("better-auth").MiddlewareInputContext<import("better-auth").MiddlewareOptions>) => Promise<{
						id: string;
						username: string;
						name: string;
						avatarUrl: string | null;
						role: "admin" | "viewer";
					}[] | undefined>>;
				}[];
			};
			endpoints: {
				getSession: import("better-auth").StrictEndpoint<"/get-session", {
					method: "GET";
					query: import("better-auth").ZodOptional<import("better-auth").ZodObject<{
						disableCookieCache: import("better-auth").ZodOptional<import("better-auth").ZodCoercedBoolean<unknown>>;
						disableRefresh: import("better-auth").ZodOptional<import("better-auth").ZodCoercedBoolean<unknown>>;
					}, import("zod/v4/core").$strip>>;
					metadata: {
						CUSTOM_SESSION: boolean;
						openapi: {
							description: string;
							responses: {
								"200": {
									description: string;
									content: {
										"application/json": {
											schema: {
												type: "array";
												nullable: boolean;
												items: {
													$ref: string;
												};
											};
										};
									};
								};
							};
						};
					};
					requireHeaders: true;
				}, {
					id: string;
					username: string;
					name: string;
					avatarUrl: string | null;
					role: "admin" | "viewer";
				} | null>;
			};
			$Infer: {
				Session: {
					id: string;
					username: string;
					name: string;
					avatarUrl: string | null;
					role: "admin" | "viewer";
				};
			};
			options: import("better-auth/plugins").CustomSessionPluginOptions | undefined;
		}
	];
	socialProviders: {
		gitlab: {
			clientId: string;
			clientSecret: string;
			scope: string[];
			disableDefaultScope: true;
			overrideUserInfoOnSignIn: true;
			mapProfileToUser: (profile: import("better-auth").GitlabProfile) => {
				emailVerified: true;
				gitlabUsername: string;
			};
		};
	};
}>;
declare class AppError extends Error {
	status: number;
	constructor(status: number, message: string);
	toResponse(): Response;
}
declare const MemorySourceSchema: z$1.ZodDiscriminatedUnion<[
	z$1.ZodObject<{
		workflow: z$1.ZodLiteral<"code-review">;
		mrIid: z$1.ZodString;
	}, z$1.z.core.$strip>,
	z$1.ZodObject<{
		workflow: z$1.ZodLiteral<"chat">;
		threadId: z$1.ZodString;
	}, z$1.z.core.$strip>,
	z$1.ZodObject<{
		workflow: z$1.ZodLiteral<"work-item-resolve">;
		issueIid: z$1.ZodString;
	}, z$1.z.core.$strip>,
	z$1.ZodObject<{
		workflow: z$1.ZodLiteral<"task-resolve">;
		threadId: z$1.ZodString;
	}, z$1.z.core.$strip>
], "workflow">;
declare const harnessConfigSchema: z.ZodObject<{
	version: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
	mr_review_instructions: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
		path: z.ZodString;
		match: z.ZodOptional<z.ZodArray<z.ZodString>>;
	}, z.core.$strip>>>>;
	work_item_resolve_instructions: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
		path: z.ZodString;
		match: z.ZodOptional<z.ZodArray<z.ZodString>>;
	}, z.core.$strip>>>>;
	exclude_branches: z.ZodDefault<z.ZodOptional<z.ZodObject<{
		source: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
		target: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
	}, z.core.$strip>>>;
	mr_review_requires_harness_reviewer: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
}, z.core.$strip>;
type Session = {
	id: string;
	username: string;
	name: string;
	avatarUrl: string | null;
};
declare const LLMProvider: {
	readonly OpenRouter: "openrouter";
	readonly Ollama: "ollama";
	readonly Sglang: "sglang";
};
type LLMProvider = (typeof LLMProvider)[keyof typeof LLMProvider];
declare const ModelName: {
	readonly Gpt5Mini: "openai/gpt-5-mini";
	readonly Gemini25FlashLite: "google/gemini-2.5-flash-lite";
	readonly ClaudeHaiku45: "anthropic/claude-haiku-4.5";
	readonly Sonnet5: "anthropic/claude-sonnet-5";
	readonly Qwen36: "qwen3.6:latest";
	readonly Qwen36_27B: "qwen3.6:27b";
	readonly Qwen35: "qwen3.5:latest";
	readonly Gemma431B: "gemma4:31b";
	readonly Qwen36Awq: "QuantTrio/Qwen3.6-35B-A3B-AWQ";
	readonly Qwen36_27BAwq: "cyankiwi/Qwen3.6-27B-AWQ-INT4";
	readonly Qwen38_27BFp8: "Qwen/Qwen3.8-27B-FP8";
};
type ModelName = (typeof ModelName)[keyof typeof ModelName];
type LLM = {
	provider: LLMProvider;
	model: ModelName;
	name: string;
	contextWindow: number;
	isDefault?: boolean;
	tokenizerRepo?: string;
};
declare const InstructionStatus: {
	readonly Loading: "loading";
	readonly LoadedAll: "loaded_all";
	readonly LoadedFiltered: "loaded_filtered";
	readonly Missing: "missing";
	readonly Failed: "failed";
};
type InstructionStatus = (typeof InstructionStatus)[keyof typeof InstructionStatus];
declare const CompletionStatus: {
	readonly Done: "done";
	readonly Partial: "partial";
	readonly Blocked: "blocked";
};
type CompletionStatus = (typeof CompletionStatus)[keyof typeof CompletionStatus];
declare const RunStep: {
	readonly PrepareWorktree: "prepare_worktree";
	readonly SetGitIdentity: "set_git_identity";
	readonly SandboxCreate: "sandbox_create";
	readonly SandboxKill: "sandbox_kill";
	readonly ClassifyIssue: "classify_issue";
	readonly CreateBranch: "create_branch";
	readonly Push: "push";
	readonly MrCreate: "mr_create";
	readonly NoChanges: "no_changes";
	readonly AssessCompletion: "assess_completion";
	readonly NotifyIssueEnd: "notify_issue_end";
	readonly UpdateMergeRequest: "update_merge_request";
};
type RunStep = (typeof RunStep)[keyof typeof RunStep];
type RunStepStartEvent = {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.PrepareWorktree;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.SetGitIdentity;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.SandboxCreate;
		image: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.SandboxKill;
		sandboxId: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.ClassifyIssue;
		prompt: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.CreateBranch;
		branchName: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.Push;
		sourceBranch: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.MrCreate;
		sourceBranch: string;
		targetBranch: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.NoChanges;
		branchName: string;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.NotifyIssueEnd;
		timestamp: number;
	};
} | {
	event: "run_step_start";
	data: {
		id: string;
		step: typeof RunStep.UpdateMergeRequest;
		timestamp: number;
	};
};
type RunStepEndEvent = {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.PrepareWorktree;
		repo: string;
		ref: string;
		cloned: boolean;
		revived: boolean;
		error: string;
		retries: number;
		maxRetries: number;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.SetGitIdentity;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.SandboxCreate;
		sandboxId: string;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.SandboxKill;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.ClassifyIssue;
		type: string;
		slug: string;
		error: string;
		retries: number;
		maxRetries: number;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.CreateBranch;
		branchName: string;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.Push;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.MrCreate;
		mrIid: string;
		mrUrl: string;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.NoChanges;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.NotifyIssueEnd;
		error: string;
		timestamp: number;
	};
} | {
	event: "run_step_end";
	data: {
		id: string;
		step: typeof RunStep.UpdateMergeRequest;
		completionStatus: CompletionStatus;
		completionSummary: string;
		error: string;
		timestamp: number;
	};
};
declare const RunKind: {
	readonly MrReview: "mr_review";
	readonly Chat: "chat";
	readonly WorkItemResolve: "work_item_resolve";
	readonly TaskResolve: "task_resolve";
};
type RunKind = (typeof RunKind)[keyof typeof RunKind];
type MrReviewRunInput = {
	kind: typeof RunKind.MrReview;
	query: {
		note: string;
		projectId: string;
		mrIid: string;
		sourceBranch: string;
		sourceSha: string;
		targetBranch: string;
		defaultBranch: string;
	};
	model: ModelName;
	reasoning: boolean;
	config: ParsedHarnessConfig;
};
type ChatRunInput = {
	kind: typeof RunKind.Chat;
	query: {
		message: string;
		images?: string[];
	};
	model: ModelName;
	reasoning: boolean;
	tools: {
		server: boolean;
		gitlab: boolean;
		webSearch: boolean;
	};
};
type WorkItemResolveRunInput = {
	kind: typeof RunKind.WorkItemResolve;
	projectPath: string;
	issueIid: string;
	defaultBranch: string;
	assignedBy: string;
	model: ModelName;
	config: ParsedHarnessConfig;
	issueKind: "issue" | "work_item";
};
type TaskResolveRunInput = {
	kind: typeof RunKind.TaskResolve;
	title: string;
	projectPath: string;
	prompt: string;
	defaultBranch: string;
	submittedBy: string;
	model: ModelName;
	config: ParsedHarnessConfig;
};
type RunInput = MrReviewRunInput | ChatRunInput | WorkItemResolveRunInput | TaskResolveRunInput;
type ResumePayload = {
	toolCallId: string;
	decision: "approve" | "reject";
};
type MessageEvent$1 = {
	event: "message";
	data: {
		id: string;
		content: string;
		reasoningContent: string;
		subagentId?: string;
	};
};
type ReasoningStartEvent = {
	event: "reasoning_start";
	data: {
		id: string;
		timestamp: number;
		subagentId?: string;
	};
};
type ReasoningEndEvent = {
	event: "reasoning_end";
	data: {
		id: string;
		timestamp: number;
		subagentId?: string;
	};
};
type ToolInputEvent = {
	event: "tool_input";
	data: {
		id: string;
		name: string;
		input: Record<string, unknown>;
		timestamp: number;
		subagentId?: string;
	};
};
type ToolOutputEvent = {
	event: "tool_output";
	data: {
		id: string;
		output?: string;
		timestamp: number;
		subagentId?: string;
	};
};
type NodeStartEvent = {
	event: "node_start";
	data: {
		node: string;
		timestamp: number;
	};
};
type LoadInstructionsNodePayload = {
	status: HarnessConfigStatus;
	parsed: HarnessConfig | null;
	instructions: {
		status: InstructionStatus;
		content: string;
	};
	error: string;
};
type AssessCompletionNodePayload = {
	status: string;
	summary: string;
	error: string;
	retries: number;
	maxRetries: number;
};
type NodeEndEvent = {
	event: "node_end";
	data: {
		node: string;
		timestamp: number;
		payload?: LoadInstructionsNodePayload | AssessCompletionNodePayload;
	};
};
type NodeEvent = NodeStartEvent | NodeEndEvent;
type AgentPromptEvent = {
	event: "agent_prompt";
	data: {
		id: string;
		systemPrompt: string;
		humanMessage: string;
		timestamp: number;
		subagentId?: string;
	};
};
type SubagentErrorEvent = {
	event: "subagent_error";
	data: {
		id: string;
		error: string;
		timestamp: number;
		subagentId: string;
	};
};
type ModelRetryEvent = {
	event: "model_retry";
	data: {
		id: string;
		count: number;
		total: number;
		error: string;
		timestamp: number;
		subagentId?: string;
	};
};
type CorrectiveNudgeStartEvent = {
	event: "corrective_nudge_start";
	data: {
		id: string;
		middleware: "DuplicateCallGuard" | "ExtractProjectMemory" | "TrailingQuestionGuard" | "NoToolCallGuard" | "DiscussionCheckGuard" | "HumanApproval";
		prompt: string;
		timestamp: number;
		subagentId?: string;
	};
};
type CorrectiveNudgeEndEvent = {
	event: "corrective_nudge_end";
	data: {
		id: string;
		error: string;
		timestamp: number;
		subagentId?: string;
	};
};
type CheckpointEvent = {
	event: "checkpoint";
	data: {
		id: string;
	};
};
type InterruptEvent = {
	event: "interrupt";
	data: {
		id: string;
		toolCallId: string;
		name: string;
		args: Record<string, unknown>;
		timestamp: number;
	};
};
type ContextUsageBreakdown = {
	systemPrompt: number;
	repoInstructions: number;
	projectMemories: number;
	toolSchemas: number;
	skillContent: number;
	messages: number;
	autocompactBuffer: number;
	freeSpace: number;
};
type ContextUsageEvent = {
	event: "context_usage";
	data: {
		promptTokens: number;
		completionTokens: number;
		totalTokens: number;
		breakdown?: ContextUsageBreakdown;
		timestamp: number;
		subagentId?: string;
	};
};
type LlmBackendWaitStartEvent = {
	event: "llm_backend_wait_start";
	data: {
		id: string;
		provider: LLMProvider;
		timestamp: number;
		subagentId?: string;
	};
};
type LlmBackendWaitEndEvent = {
	event: "llm_backend_wait_end";
	data: {
		id: string;
		timestamp: number;
		subagentId?: string;
	};
};
type QueueWaitEvent = {
	event: "queue_wait";
	data: {
		waitMs: number;
		timestamp: number;
	};
};
type SummarizeContextStartEvent = {
	event: "summarize_context_start";
	data: {
		id: string;
		prompt: string;
		timestamp: number;
	};
};
type SummarizeContextEndEvent = {
	event: "summarize_context_end";
	data: {
		id: string;
		messagesBefore: number;
		messagesAfter: number;
		summary: string;
		error: string;
		retries: number;
		maxRetries: number;
		timestamp: number;
	};
};
type CriticStartEventData = {
	id: string;
	prompt: string;
	timestamp: number;
};
type CriticEndEventData = {
	id: string;
	content: string;
	verdicts: {
		id: string;
		drop: boolean;
	}[];
	dropped: {
		id: string;
		body: string;
	}[];
	failed: {
		id: string;
		body: string;
	}[];
	error: string;
	retries: number;
	maxRetries: number;
	timestamp: number;
};
type CommentCriticStartEvent = {
	event: "comment_critic_start";
	data: CriticStartEventData;
};
type CommentCriticEndEvent = {
	event: "comment_critic_end";
	data: CriticEndEventData;
};
type ReplyCriticStartEvent = {
	event: "reply_critic_start";
	data: CriticStartEventData;
};
type ReplyCriticEndEvent = {
	event: "reply_critic_end";
	data: CriticEndEventData;
};
type ExtractProjectMemoryStartEvent = {
	event: "extract_project_memory_start";
	data: {
		id: string;
		categories: MemoryCategory[];
		prompt: string;
		timestamp: number;
	};
};
type ExtractProjectMemoryEndEvent = {
	event: "extract_project_memory_end";
	data: {
		id: string;
		decisions: {
			action: "add" | "update" | "retire" | "skip";
			category?: MemoryCategory;
			targetId?: string;
			candidateTitle?: string;
			matchedId?: string;
			title?: string;
			content?: string;
			evidence?: string[];
			reason?: string;
		}[];
		error: string;
		missed: number;
		retries: number;
		maxRetries: number;
		timestamp: number;
	};
};
type RunStepEvent = RunStepStartEvent | RunStepEndEvent;
type LangGraphEvent = MessageEvent$1 | ReasoningStartEvent | ReasoningEndEvent | CheckpointEvent | ToolInputEvent | ToolOutputEvent;
type WriterEvent = ToolInputEvent | ToolOutputEvent | MessageEvent$1 | ReasoningStartEvent | ReasoningEndEvent | NodeEvent | AgentPromptEvent | SubagentErrorEvent | ModelRetryEvent | ContextUsageEvent | LlmBackendWaitStartEvent | LlmBackendWaitEndEvent | SummarizeContextStartEvent | SummarizeContextEndEvent | CommentCriticStartEvent | CommentCriticEndEvent | ReplyCriticStartEvent | ReplyCriticEndEvent | CorrectiveNudgeStartEvent | CorrectiveNudgeEndEvent | ExtractProjectMemoryStartEvent | ExtractProjectMemoryEndEvent | InterruptEvent;
type WorkflowEvent = LangGraphEvent | WriterEvent;
type RunEvent = RunStepEvent | QueueWaitEvent | WorkflowEvent;
declare const RunStatus: {
	readonly QUEUED: "queued";
	readonly RUNNING: "running";
	readonly COMPLETED: "completed";
	readonly FAILED: "failed";
	readonly SUPERSEDED: "superseded";
	readonly INTERRUPTED: "interrupted";
};
type RunStatus = (typeof RunStatus)[keyof typeof RunStatus];
type Timestamp = ColumnType<Date, never, never>;
type ThreadMetadata = Record<string, unknown>;
interface ThreadTable {
	id: ColumnType<string, never, never>;
	title: string;
	kind: ColumnType<RunKind, RunKind, never>;
	user_id: ColumnType<string | null, string | null | undefined, never>;
	metadata: ColumnType<ThreadMetadata | null>;
	archived_at: ColumnType<Date | null, never, Date | null>;
	created_at: Timestamp;
	updated_at: Timestamp;
}
type NudgeStats = Record<string, {
	fired: number;
	resolved: number;
	escalated: number;
}>;
declare const MemoryCategory: {
	readonly knowledge: "knowledge";
	readonly preference: "preference";
	readonly lesson: "lesson";
	readonly decision: "decision";
};
type MemoryCategory = (typeof MemoryCategory)[keyof typeof MemoryCategory];
type MemorySource = z.infer<typeof MemorySourceSchema>;
interface MemoryTable {
	id: ColumnType<string, never, never>;
	project_id: ColumnType<string | null, string | null | undefined, never>;
	user_id: ColumnType<string | null, string | null | undefined, never>;
	category: MemoryCategory;
	title: string;
	content: string;
	evidence: string[];
	source: MemorySource;
	created_at: Timestamp;
	updated_at: Timestamp;
}
declare const ScheduleStatus: {
	readonly Active: "active";
	readonly Paused: "paused";
	readonly Cancelled: "cancelled";
	readonly Completed: "completed";
};
type ScheduleStatus = (typeof ScheduleStatus)[keyof typeof ScheduleStatus];
type ScheduleRecurrence = {
	freq: "daily";
	time: string;
} | {
	freq: "weekly";
	time: string;
	daysOfWeek: number[];
} | {
	freq: "monthly";
	time: string;
	dayOfMonth: number;
};
type Thread = Selectable<ThreadTable>;
type ThreadWithRunStatus = Thread & {
	latest_run_status: RunStatus | null;
	latest_run_started_at: Date | null;
	latest_run_completed_at: Date | null;
};
type Memory = Selectable<MemoryTable>;
type MemoryCategoryEntryMap = Record<MemoryCategory, Memory[]>;
type WSEvent = {
	type: "thread:upserted";
	payload: ThreadWithRunStatus;
};
type HarnessConfig = z.infer<typeof harnessConfigSchema>;
declare const HarnessConfigStatus: {
	readonly Ok: "ok";
	readonly Missing: "missing";
	readonly Invalid: "invalid";
};
type HarnessConfigStatus = (typeof HarnessConfigStatus)[keyof typeof HarnessConfigStatus];
type ParsedHarnessConfig = {
	parsed: HarnessConfig | null;
	status: HarnessConfigStatus;
};
export declare const app: Elysia<"", {
	decorator: {};
	store: {};
	derive: {};
	resolve: {};
}, {
	typebox: {};
	error: {
		readonly AppError: AppError;
	};
} & {
	typebox: {};
	error: {};
}, {
	schema: {};
	standaloneSchema: {};
	macro: {};
	macroFn: {};
	parser: {};
	response: {};
} & {
	schema: {};
	standaloneSchema: {};
	macro: {};
	macroFn: {};
	parser: {};
	response: {};
} & {
	schema: {};
	standaloneSchema: {};
	macro: Partial<{
		readonly auth: boolean;
	}>;
	macroFn: {
		readonly auth: {
			readonly resolve: ({ request, status }: {
				body: unknown;
				query: Record<string, string>;
				params: {};
				headers: Record<string, string | undefined>;
				cookie: Record<string, import("elysia").Cookie<unknown>>;
				server: import("elysia/universal/server").Server | null;
				redirect: import("elysia").redirect;
				set: {
					headers: import("elysia").HTTPHeaders;
					status?: number | keyof import("elysia").StatusMap;
					redirect?: string;
					cookie?: Record<string, import("elysia/cookies").ElysiaCookie>;
				};
				path: string;
				route: string;
				request: Request;
				store: {};
				status: <const Code extends number | keyof import("elysia").StatusMap, const T = Code extends 100 | 404 | 403 | 409 | 400 | 405 | 502 | 413 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 300 | 301 | 302 | 303 | 304 | 307 | 308 | 401 | 402 | 406 | 407 | 408 | 410 | 411 | 412 | 414 | 415 | 416 | 417 | 418 | 420 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511 ? {
					readonly 100: "Continue";
					readonly 101: "Switching Protocols";
					readonly 102: "Processing";
					readonly 103: "Early Hints";
					readonly 200: "OK";
					readonly 201: "Created";
					readonly 202: "Accepted";
					readonly 203: "Non-Authoritative Information";
					readonly 204: "No Content";
					readonly 205: "Reset Content";
					readonly 206: "Partial Content";
					readonly 207: "Multi-Status";
					readonly 208: "Already Reported";
					readonly 300: "Multiple Choices";
					readonly 301: "Moved Permanently";
					readonly 302: "Found";
					readonly 303: "See Other";
					readonly 304: "Not Modified";
					readonly 307: "Temporary Redirect";
					readonly 308: "Permanent Redirect";
					readonly 400: "Bad Request";
					readonly 401: "Unauthorized";
					readonly 402: "Payment Required";
					readonly 403: "Forbidden";
					readonly 404: "Not Found";
					readonly 405: "Method Not Allowed";
					readonly 406: "Not Acceptable";
					readonly 407: "Proxy Authentication Required";
					readonly 408: "Request Timeout";
					readonly 409: "Conflict";
					readonly 410: "Gone";
					readonly 411: "Length Required";
					readonly 412: "Precondition Failed";
					readonly 413: "Payload Too Large";
					readonly 414: "URI Too Long";
					readonly 415: "Unsupported Media Type";
					readonly 416: "Range Not Satisfiable";
					readonly 417: "Expectation Failed";
					readonly 418: "I'm a teapot";
					readonly 420: "Enhance Your Calm";
					readonly 421: "Misdirected Request";
					readonly 422: "Unprocessable Content";
					readonly 423: "Locked";
					readonly 424: "Failed Dependency";
					readonly 425: "Too Early";
					readonly 426: "Upgrade Required";
					readonly 428: "Precondition Required";
					readonly 429: "Too Many Requests";
					readonly 431: "Request Header Fields Too Large";
					readonly 451: "Unavailable For Legal Reasons";
					readonly 500: "Internal Server Error";
					readonly 501: "Not Implemented";
					readonly 502: "Bad Gateway";
					readonly 503: "Service Unavailable";
					readonly 504: "Gateway Timeout";
					readonly 505: "HTTP Version Not Supported";
					readonly 506: "Variant Also Negotiates";
					readonly 507: "Insufficient Storage";
					readonly 508: "Loop Detected";
					readonly 510: "Not Extended";
					readonly 511: "Network Authentication Required";
				}[Code] : Code>(code: Code, response?: T) => import("elysia").ElysiaCustomStatusResponse<Code, T, Code extends "Continue" | "Switching Protocols" | "Processing" | "Early Hints" | "OK" | "Created" | "Accepted" | "Non-Authoritative Information" | "No Content" | "Reset Content" | "Partial Content" | "Multi-Status" | "Already Reported" | "Multiple Choices" | "Moved Permanently" | "Found" | "See Other" | "Not Modified" | "Temporary Redirect" | "Permanent Redirect" | "Bad Request" | "Unauthorized" | "Payment Required" | "Forbidden" | "Not Found" | "Method Not Allowed" | "Not Acceptable" | "Proxy Authentication Required" | "Request Timeout" | "Conflict" | "Gone" | "Length Required" | "Precondition Failed" | "Payload Too Large" | "URI Too Long" | "Unsupported Media Type" | "Range Not Satisfiable" | "Expectation Failed" | "I'm a teapot" | "Enhance Your Calm" | "Misdirected Request" | "Unprocessable Content" | "Locked" | "Failed Dependency" | "Too Early" | "Upgrade Required" | "Precondition Required" | "Too Many Requests" | "Request Header Fields Too Large" | "Unavailable For Legal Reasons" | "Internal Server Error" | "Not Implemented" | "Bad Gateway" | "Service Unavailable" | "Gateway Timeout" | "HTTP Version Not Supported" | "Variant Also Negotiates" | "Insufficient Storage" | "Loop Detected" | "Not Extended" | "Network Authentication Required" ? {
					readonly Continue: 100;
					readonly "Switching Protocols": 101;
					readonly Processing: 102;
					readonly "Early Hints": 103;
					readonly OK: 200;
					readonly Created: 201;
					readonly Accepted: 202;
					readonly "Non-Authoritative Information": 203;
					readonly "No Content": 204;
					readonly "Reset Content": 205;
					readonly "Partial Content": 206;
					readonly "Multi-Status": 207;
					readonly "Already Reported": 208;
					readonly "Multiple Choices": 300;
					readonly "Moved Permanently": 301;
					readonly Found: 302;
					readonly "See Other": 303;
					readonly "Not Modified": 304;
					readonly "Temporary Redirect": 307;
					readonly "Permanent Redirect": 308;
					readonly "Bad Request": 400;
					readonly Unauthorized: 401;
					readonly "Payment Required": 402;
					readonly Forbidden: 403;
					readonly "Not Found": 404;
					readonly "Method Not Allowed": 405;
					readonly "Not Acceptable": 406;
					readonly "Proxy Authentication Required": 407;
					readonly "Request Timeout": 408;
					readonly Conflict: 409;
					readonly Gone: 410;
					readonly "Length Required": 411;
					readonly "Precondition Failed": 412;
					readonly "Payload Too Large": 413;
					readonly "URI Too Long": 414;
					readonly "Unsupported Media Type": 415;
					readonly "Range Not Satisfiable": 416;
					readonly "Expectation Failed": 417;
					readonly "I'm a teapot": 418;
					readonly "Enhance Your Calm": 420;
					readonly "Misdirected Request": 421;
					readonly "Unprocessable Content": 422;
					readonly Locked: 423;
					readonly "Failed Dependency": 424;
					readonly "Too Early": 425;
					readonly "Upgrade Required": 426;
					readonly "Precondition Required": 428;
					readonly "Too Many Requests": 429;
					readonly "Request Header Fields Too Large": 431;
					readonly "Unavailable For Legal Reasons": 451;
					readonly "Internal Server Error": 500;
					readonly "Not Implemented": 501;
					readonly "Bad Gateway": 502;
					readonly "Service Unavailable": 503;
					readonly "Gateway Timeout": 504;
					readonly "HTTP Version Not Supported": 505;
					readonly "Variant Also Negotiates": 506;
					readonly "Insufficient Storage": 507;
					readonly "Loop Detected": 508;
					readonly "Not Extended": 510;
					readonly "Network Authentication Required": 511;
				}[Code] : Code>;
			}) => Promise<import("elysia").ElysiaCustomStatusResponse<401, "Unauthorized", 401> | {
				session: Session;
			}>;
		};
	};
	parser: {};
	response: {};
}, {
	health: {
		get: {
			body: unknown;
			params: {};
			query: unknown;
			headers: unknown;
			response: {
				200: {
					status: string;
				};
			};
		};
	};
} & {
	api: {};
} & {
	api: {
		uploads: {
			post: {
				body: unknown;
				params: {};
				query: unknown;
				headers: unknown;
				response: {
					200: {
						ref: string;
					};
				};
			};
		};
	} & {
		uploads: {
			":filename": {
				get: {
					body: unknown;
					params: {
						filename: string;
					} & {};
					query: unknown;
					headers: unknown;
					response: {
						200: import("node:fs").ReadStream;
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			get: {
				body: {};
				params: {};
				query: {
					title?: string | undefined;
					kinds?: ("chat" | "mr_review" | "work_item_resolve" | "task_resolve")[] | undefined;
					projects?: string[] | undefined;
					statuses?: string[] | undefined;
					limit?: number | undefined;
					offset?: number | undefined;
				};
				headers: {};
				response: {
					200: {
						data: {
							title: string;
							kind: RunKind;
							id: string;
							user_id: string | null;
							metadata: ThreadMetadata | null;
							archived_at: Date | null;
							created_at: Date;
							updated_at: Date;
							latest_run_status: RunStatus | null;
							latest_run_started_at: Date | null;
							latest_run_completed_at: Date | null;
							run_count: number;
							failure_count: number;
						}[];
						total: number;
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			projects: {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: string[];
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			post: {
				body: {
					title: string;
					kind: "chat" | "mr_review" | "work_item_resolve" | "task_resolve";
				};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						title: string;
						kind: RunKind;
						id: string;
						user_id: string | null;
						metadata: ThreadMetadata | null;
						archived_at: Date | null;
						created_at: Date;
						updated_at: Date;
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				get: {
					body: {};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						200: {
							title: string;
							kind: RunKind;
							id: string;
							user_id: string | null;
							metadata: ThreadMetadata | null;
							archived_at: Date | null;
							created_at: Date;
							updated_at: Date;
							latest_run_status: RunStatus | null;
							latest_run_started_at: Date | null;
							latest_run_completed_at: Date | null;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				patch: {
					body: {
						title: string;
					};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				delete: {
					body: {};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					get: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							200: {
								input: RunInput;
								kind: RunKind;
								error: string | null;
								status: RunStatus;
								id: string;
								created_at: Date;
								updated_at: Date;
								thread_id: string;
								events: RunEvent[];
								parent_checkpoint_id: string | null;
								resume_payload: ResumePayload | null;
								started_at: Date | null;
								completed_at: Date | null;
							}[];
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					":runId": {
						get: {
							body: {};
							params: {
								id: string;
								runId: string;
							};
							query: {};
							headers: {};
							response: {
								200: {
									input: RunInput;
									kind: RunKind;
									error: string | null;
									status: RunStatus;
									id: string;
									created_at: Date;
									updated_at: Date;
									thread_id: string;
									events: RunEvent[];
									parent_checkpoint_id: string | null;
									resume_payload: ResumePayload | null;
									started_at: Date | null;
									completed_at: Date | null;
								};
								422: {
									type: "validation";
									on: string;
									summary?: string;
									message?: string;
									found?: unknown;
									property?: string;
									expected?: string;
								};
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					":runId": {
						stream: {
							get: {
								body: {};
								params: {
									id: string;
									runId: string;
								};
								query: {};
								headers: {};
								response: {
									200: AsyncGenerator<RunEvent | {
										readonly event: "run_end";
										readonly data: {
											readonly status: RunStatus;
											readonly error: string | null;
											readonly started_at: Date | null;
											readonly completed_at: Date | null;
											readonly updated_at: Date;
										};
									}, void, unknown>;
									422: {
										type: "validation";
										on: string;
										summary?: string;
										message?: string;
										found?: unknown;
										property?: string;
										expected?: string;
									};
								};
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					post: {
						body: {
							reasoning?: boolean | undefined;
							images?: string[] | undefined;
							message: string;
							model: "openai/gpt-5-mini" | "google/gemini-2.5-flash-lite" | "anthropic/claude-haiku-4.5" | "anthropic/claude-sonnet-5" | "qwen3.6:latest" | "qwen3.6:27b" | "qwen3.5:latest" | "gemma4:31b" | "QuantTrio/Qwen3.6-35B-A3B-AWQ" | "cyankiwi/Qwen3.6-27B-AWQ-INT4" | "Qwen/Qwen3.8-27B-FP8";
							tools: {
								gitlab: boolean;
								server: boolean;
								webSearch: boolean;
							};
						};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							200: {
								input: RunInput;
								kind: RunKind;
								error: string | null;
								status: RunStatus;
								id: string;
								created_at: Date;
								updated_at: Date;
								thread_id: string;
								events: RunEvent[];
								parent_checkpoint_id: string | null;
								resume_payload: ResumePayload | null;
								started_at: Date | null;
								completed_at: Date | null;
							};
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					":runId": {
						retry: {
							post: {
								body: {
									checkpointId?: string | undefined;
								};
								params: {
									id: string;
									runId: string;
								};
								query: {};
								headers: {};
								response: {
									200: {
										input: RunInput;
										kind: RunKind;
										error: string | null;
										status: RunStatus;
										id: string;
										created_at: Date;
										updated_at: Date;
										thread_id: string;
										events: RunEvent[];
										parent_checkpoint_id: string | null;
										resume_payload: ResumePayload | null;
										started_at: Date | null;
										completed_at: Date | null;
									};
									422: {
										type: "validation";
										on: string;
										summary?: string;
										message?: string;
										found?: unknown;
										property?: string;
										expected?: string;
									};
								};
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					":runId": {
						decision: {
							post: {
								body: {
									decision: "approve" | "reject";
									toolCallId: string;
								};
								params: {
									id: string;
									runId: string;
								};
								query: {};
								headers: {};
								response: {
									200: {
										input: RunInput;
										kind: RunKind;
										error: string | null;
										status: RunStatus;
										id: string;
										created_at: Date;
										updated_at: Date;
										thread_id: string;
										events: RunEvent[];
										parent_checkpoint_id: string | null;
										resume_payload: ResumePayload | null;
										started_at: Date | null;
										completed_at: Date | null;
									};
									422: {
										type: "validation";
										on: string;
										summary?: string;
										message?: string;
										found?: unknown;
										property?: string;
										expected?: string;
									};
								};
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		threads: {
			":id": {
				runs: {
					":runId": {
						abort: {
							post: {
								body: {};
								params: {
									id: string;
									runId: string;
								};
								query: {};
								headers: {};
								response: {
									422: {
										type: "validation";
										on: string;
										summary?: string;
										message?: string;
										found?: unknown;
										property?: string;
										expected?: string;
									};
								};
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		workflows: {
			get: {
				body: {};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						id: string;
						name: string;
						description: string;
						status: "queued" | "running" | "idle";
						totalRuns: number;
						activeRuns: number;
						lastRunAt: Date | null;
						startMode: "immediate" | "queued";
						interruptible: boolean;
					}[];
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		workflows: {
			":id": {
				get: {
					body: {};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						200: {
							id: string;
							name: string;
							description: string;
							status: "queued" | "running" | "idle";
							totalRuns: number;
							activeRuns: number;
							lastRunAt: Date | null;
							startMode: "immediate" | "queued";
							interruptible: boolean;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		workflows: {
			":id": {
				graph: {
					get: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							200: {
								mermaid: string;
							};
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		"task-resolve": {
			post: {
				body: {
					title: string;
					prompt: string;
					repoUrl: string;
				};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						thread: {
							title: string;
							kind: RunKind;
							id: string;
							user_id: string | null;
							metadata: ThreadMetadata | null;
							archived_at: Date | null;
							created_at: Date;
							updated_at: Date;
						};
						run: {
							input: RunInput;
							kind: RunKind;
							error: string | null;
							status: RunStatus;
							id: string;
							created_at: Date;
							updated_at: Date;
							thread_id: string;
							events: RunEvent[];
							parent_checkpoint_id: string | null;
							resume_payload: ResumePayload | null;
							started_at: Date | null;
							completed_at: Date | null;
						};
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			get: {
				body: {};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						nextRun: Date | null;
						repoUrl: string;
						title: string;
						status: ScheduleStatus;
						id: string;
						created_at: Date;
						updated_at: Date;
						project_path: string;
						prompt: string;
						default_branch: string;
						created_by: string;
						recurrence: ScheduleRecurrence | null;
						scheduled_for: Date;
						timezone: string;
						end_date: Date | null;
					}[];
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				get: {
					body: {};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						200: {
							runs: {
								title: string;
								kind: RunKind;
								id: string;
								user_id: string | null;
								metadata: ThreadMetadata | null;
								archived_at: Date | null;
								created_at: Date;
								updated_at: Date;
								latest_run_status: RunStatus | null;
								latest_run_started_at: Date | null;
								latest_run_completed_at: Date | null;
							}[];
							nextRun: Date | null;
							repoUrl: string;
							title: string;
							status: ScheduleStatus;
							id: string;
							created_at: Date;
							updated_at: Date;
							project_path: string;
							prompt: string;
							default_branch: string;
							created_by: string;
							recurrence: ScheduleRecurrence | null;
							scheduled_for: Date;
							timezone: string;
							end_date: Date | null;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			post: {
				body: {
					title: string;
					prompt: string;
					timezone: string;
					repoUrl: string;
					scheduledFor: string;
				} | {
					endDate?: string | undefined;
					title: string;
					prompt: string;
					recurrence: {
						time: string;
						freq: "daily";
					} | {
						time: string;
						freq: "weekly";
						daysOfWeek: number[];
					} | {
						time: string;
						freq: "monthly";
						dayOfMonth: number;
					};
					timezone: string;
					repoUrl: string;
				};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						title: string;
						status: ScheduleStatus;
						id: string;
						created_at: Date;
						updated_at: Date;
						project_path: string;
						prompt: string;
						default_branch: string;
						created_by: string;
						recurrence: ScheduleRecurrence | null;
						scheduled_for: Date;
						timezone: string;
						end_date: Date | null;
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				patch: {
					body: {
						title: string;
						prompt: string;
						timezone: string;
						repoUrl: string;
						scheduledFor: string;
					} | {
						endDate?: string | undefined;
						title: string;
						prompt: string;
						recurrence: {
							time: string;
							freq: "daily";
						} | {
							time: string;
							freq: "weekly";
							daysOfWeek: number[];
						} | {
							time: string;
							freq: "monthly";
							dayOfMonth: number;
						};
						timezone: string;
						repoUrl: string;
					};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						200: {
							title: string;
							status: ScheduleStatus;
							id: string;
							created_at: Date;
							updated_at: Date;
							project_path: string;
							prompt: string;
							default_branch: string;
							created_by: string;
							recurrence: ScheduleRecurrence | null;
							scheduled_for: Date;
							timezone: string;
							end_date: Date | null;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				pause: {
					post: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				resume: {
					post: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				cancel: {
					post: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		schedules: {
			":id": {
				"run-now": {
					post: {
						body: {};
						params: {
							id: string;
						};
						query: {};
						headers: {};
						response: {
							200: {
								thread: {
									title: string;
									kind: RunKind;
									id: string;
									user_id: string | null;
									metadata: ThreadMetadata | null;
									archived_at: Date | null;
									created_at: Date;
									updated_at: Date;
								};
								run: {
									input: RunInput;
									kind: RunKind;
									error: string | null;
									status: RunStatus;
									id: string;
									created_at: Date;
									updated_at: Date;
									thread_id: string;
									events: RunEvent[];
									parent_checkpoint_id: string | null;
									resume_payload: ResumePayload | null;
									started_at: Date | null;
									completed_at: Date | null;
								};
							};
							422: {
								type: "validation";
								on: string;
								summary?: string;
								message?: string;
								found?: unknown;
								property?: string;
								expected?: string;
							};
						};
					};
				};
			};
		};
	};
} & {
	api: {
		queue: {
			get: {
				body: {};
				params: {};
				query: {
					kind: "mr_review" | "work_item_resolve" | "task_resolve";
				};
				headers: {};
				response: {
					200: {
						active: number;
						waiting: number;
						delayed: number;
						jobs: {
							runId?: string;
							threadId: string;
							state: string;
							delayRemaining?: number;
						}[];
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		users: {
			get: {
				body: {};
				params: {};
				query: {};
				headers: {};
				response: {
					200: {
						total: number;
						active: number;
					};
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		analytics: {
			overview: {
				get: {
					body: {};
					params: {};
					query: {
						since?: string | undefined;
						kind: "chat" | "mr_review" | "work_item_resolve" | "task_resolve";
					};
					headers: {};
					response: {
						200: {
							total: number;
							distinctThreads: number;
							avgRunsPerThread: number | null;
							successful: number;
							errorKinds: {
								timeout: number;
								guardAbort: number;
								manualAbort: number;
								modelError: number;
								serverRestart: number;
								generationLoop: number;
							};
							avgDurationMs: number | null;
							medianDurationMs: number | null;
							p95DurationMs: number | null;
							avgLlmCalls: number | null;
							avgToolCalls: number | null;
							avgUniqueTools: number | null;
							avgRepeatedToolCalls: number | null;
							avgModelRetries: number | null;
							avgCheckpoints: number | null;
							avgTotalTokens: number | null;
							avgMaxContextSize: number | null;
							avgQueueWaitMs: number | null;
							avgLlmBackendWaitMs: number | null;
							subagentRuns: number;
							nudgeStats: NudgeStats;
							commentCritic: {
								runsScreened: number;
								runsWithError: number;
								verdicts: number;
								dropped: number;
								failed: number;
							};
							memoryCurator: {
								runsRun: number;
								runsWithError: number;
								added: number;
								updated: number;
								retired: number;
								skipped: number;
								missed: number;
							};
							ownComments: {
								total: number;
								resolved: number;
								acceptanceRate: number | null;
							};
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		analytics: {
			"by-repo": {
				get: {
					body: {};
					params: {};
					query: {
						limit?: number | undefined;
						offset?: number | undefined;
						projectId?: string | undefined;
						since?: string | undefined;
						kind: "chat" | "mr_review" | "work_item_resolve" | "task_resolve";
					};
					headers: {};
					response: {
						200: {
							repos: {
								repo: string;
								totalRuns: number;
								totalThreads: number;
								failedRuns: number;
								avgDurationMs: number | null;
								avgRunsPerThread: number;
							}[];
							total: number;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		analytics: {
			trend: {
				get: {
					body: {};
					params: {};
					query: {
						since?: string | undefined;
						kind: "chat" | "mr_review" | "work_item_resolve" | "task_resolve";
					};
					headers: {};
					response: {
						200: {
							date: string;
							avgDurationMs: number;
							avgQueueWaitMs: number | null;
							avgLlmBackendWaitMs: number;
							total: number;
							successRate: number | null;
							timeout: number;
							guardAbort: number;
							manualAbort: number;
							modelError: number;
							serverRestart: number;
							generationLoop: number;
						}[];
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		analytics: {
			usage: {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: {
							totalUsers: number;
							totalReviews: number;
							totalChats: number;
							totalProjectMemories: number;
							totalPersonalMemories: number;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		memories: {
			get: {
				body: {};
				params: {};
				query: {
					projectId?: string | undefined;
					scope?: "personal" | undefined;
					categories?: ("knowledge" | "preference" | "lesson" | "decision")[] | undefined;
				};
				headers: {};
				response: {
					200: MemoryCategoryEntryMap;
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		memories: {
			projects: {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: Record<string, number>;
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		memories: {
			personal: {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: number;
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		memories: {
			":id": {
				delete: {
					body: {};
					params: {
						id: string;
					};
					query: {};
					headers: {};
					response: {
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		settings: {
			"openrouter-key": {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: {
							configured: boolean;
							last4: string;
						} | {
							configured: boolean;
							last4: null;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		settings: {
			"openrouter-key": {
				put: {
					body: {
						apiKey: string;
					};
					params: {};
					query: {};
					headers: {};
					response: {
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		models: {
			get: {
				body: {};
				params: {};
				query: {};
				headers: {};
				response: {
					200: LLM[];
					422: {
						type: "validation";
						on: string;
						summary?: string;
						message?: string;
						found?: unknown;
						property?: string;
						expected?: string;
					};
				};
			};
		};
	};
} & {
	api: {
		monitoring: {
			"stack-containers": {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: {
							name: string;
							cpuPercent: number;
							memoryUsedBytes: number;
							memoryLimitBytes: number;
							error?: string;
						}[];
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		monitoring: {
			"sandbox-fleet": {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: {
							count: number;
							reachableCount: number;
							cpuUsedPercentageTotal: number;
							memoryUsedMiBTotal: number;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	api: {
		monitoring: {
			"disk-usage": {
				get: {
					body: {};
					params: {};
					query: {};
					headers: {};
					response: {
						200: {
							app: number;
							postgres: number;
							redis: number;
							supermemory: number;
							opensandbox: number;
						};
						422: {
							type: "validation";
							on: string;
							summary?: string;
							message?: string;
							found?: unknown;
							property?: string;
							expected?: string;
						};
					};
				};
			};
		};
	};
} & {
	webhooks: {};
} & {
	webhooks: {
		gitlab: {
			post: {
				body: unknown;
				params: {};
				query: unknown;
				headers: unknown;
				response: {
					200: {
						received: boolean;
						status: string;
						reason: string;
						detail?: undefined;
					} | {
						received: boolean;
						status: string;
						detail: string;
						reason?: undefined;
					};
					401: "Unauthorized";
				};
			};
		};
	};
} & {
	ws: {
		subscribe: {
			body: {};
			params: {};
			query: {};
			headers: {};
			response: {
				200: WSEvent;
				401: "Unauthorized";
				422: {
					type: "validation";
					on: string;
					summary?: string;
					message?: string;
					found?: unknown;
					property?: string;
					expected?: string;
				};
			};
		};
	};
}, {
	derive: {};
	resolve: {};
	schema: {};
	standaloneSchema: {};
	response: {};
}, {
	derive: {};
	resolve: {};
	schema: {};
	standaloneSchema: {};
	response: {
		200: Response;
	};
} & {
	derive: {};
	resolve: {};
	schema: {};
	standaloneSchema: {};
	response: {};
}>;
export type App = typeof app;
export type Auth = typeof auth;

export {};
